// Generated by CoffeeScript 1.6.2
(function() {
  var jasmineFolder, jsFolder, requiredModules, specsFolder;

  jasmineFolder = "lib/jasmine-1.3.1/";

  specsFolder = "specs/";

  jsFolder = "../assets/javascripts/";

  require.config({
    baseUrl: "/tests/",
    urlArgs: "cb=" + Math.random(),
    paths: {
      admaxim: "http://apptrack.admaxim.com/ads/track/admaxim_track",
      jasmine: jasmineFolder + "jasmine",
      jasmineHtml: jasmineFolder + "jasmine-html",
      jasmineJquery: "lib/jasmine-jquery",
      jquery: "http://code.jquery.com/jquery-2.0.3.min",
      zepto: jsFolder + "lib/zepto.min",
      underscore: jsFolder + 'lib/underscore-min',
      utils: jsFolder + "utils",
      gallery: jsFolder + "gallery",
      release: jsFolder + "release_date"
    },
    shim: {
      jasmine: {
        exports: "jasmine"
      },
      jasmineHtml: ["jasmine"],
      jasmineJquery: ["jasmine"],
      jquery: {
        exports: "$"
      }
    }
  });

  requiredModules = ["jquery", "jasmine", "jasmineHtml", "jasmineJquery"];

  require(requiredModules, function() {
    var htmlReporter, jasmineEnv, specs;

    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;
    htmlReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(htmlReporter);
    jasmineEnv.specFilter = function(spec) {
      return htmlReporter.specFilter(spec);
    };
    specs = [specsFolder + "detect_spec", specsFolder + "gallery_spec", specsFolder + "manage_elements_spec", specsFolder + "loader_spec", specsFolder + "release_spec", specsFolder + "touch_spec"];
    return require(specs, function() {
      return jasmineEnv.execute();
    });
  });

}).call(this);
